ALTER TABLE USERS ADD PASSWORD VARCHAR(100);
UPDATE USERS SET PASSWORD = '$2a$12$JmB.O3fBcwg7i2KW9OhM5OTtncilEpBQCfFiBcaeu7VXWAIGrCCvy' WHERE USER_NAME = 'seth_username';
ALTER TABLE USERS MODIFY PASSWORD VARCHAR(100) NOT NULL;